/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSimpleJValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.paris10.miage.simpleJ.SimpleJPackage.eINSTANCE);
		return result;
	}
	
}
