/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.ui.tests;

import com.google.inject.Injector;
import fr.paris10.miage.SimpleJ.ui.internal.SimpleJActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SimpleJUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimpleJActivator.getInstance().getInjector("fr.paris10.miage.SimpleJ");
	}

}
