/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.simpleJ.impl;

import fr.paris10.miage.simpleJ.Acces;
import fr.paris10.miage.simpleJ.Attribut;
import fr.paris10.miage.simpleJ.Delegation;
import fr.paris10.miage.simpleJ.SimpleJPackage;
import fr.paris10.miage.simpleJ.Type;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribut</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.paris10.miage.simpleJ.impl.AttributImpl#getAcces <em>Acces</em>}</li>
 *   <li>{@link fr.paris10.miage.simpleJ.impl.AttributImpl#getDelegue <em>Delegue</em>}</li>
 *   <li>{@link fr.paris10.miage.simpleJ.impl.AttributImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.paris10.miage.simpleJ.impl.AttributImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributImpl extends MinimalEObjectImpl.Container implements Attribut
{
  /**
   * The default value of the '{@link #getAcces() <em>Acces</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAcces()
   * @generated
   * @ordered
   */
  protected static final Acces ACCES_EDEFAULT = Acces.ACCESS_VAR;

  /**
   * The cached value of the '{@link #getAcces() <em>Acces</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAcces()
   * @generated
   * @ordered
   */
  protected Acces acces = ACCES_EDEFAULT;

  /**
   * The cached value of the '{@link #getDelegue() <em>Delegue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDelegue()
   * @generated
   * @ordered
   */
  protected Delegation delegue;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Type type;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimpleJPackage.Literals.ATTRIBUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Acces getAcces()
  {
    return acces;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAcces(Acces newAcces)
  {
    Acces oldAcces = acces;
    acces = newAcces == null ? ACCES_EDEFAULT : newAcces;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleJPackage.ATTRIBUT__ACCES, oldAcces, acces));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Delegation getDelegue()
  {
    return delegue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDelegue(Delegation newDelegue, NotificationChain msgs)
  {
    Delegation oldDelegue = delegue;
    delegue = newDelegue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimpleJPackage.ATTRIBUT__DELEGUE, oldDelegue, newDelegue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDelegue(Delegation newDelegue)
  {
    if (newDelegue != delegue)
    {
      NotificationChain msgs = null;
      if (delegue != null)
        msgs = ((InternalEObject)delegue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimpleJPackage.ATTRIBUT__DELEGUE, null, msgs);
      if (newDelegue != null)
        msgs = ((InternalEObject)newDelegue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimpleJPackage.ATTRIBUT__DELEGUE, null, msgs);
      msgs = basicSetDelegue(newDelegue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleJPackage.ATTRIBUT__DELEGUE, newDelegue, newDelegue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleJPackage.ATTRIBUT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Type newType, NotificationChain msgs)
  {
    Type oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimpleJPackage.ATTRIBUT__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(Type newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimpleJPackage.ATTRIBUT__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimpleJPackage.ATTRIBUT__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimpleJPackage.ATTRIBUT__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimpleJPackage.ATTRIBUT__DELEGUE:
        return basicSetDelegue(null, msgs);
      case SimpleJPackage.ATTRIBUT__TYPE:
        return basicSetType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimpleJPackage.ATTRIBUT__ACCES:
        return getAcces();
      case SimpleJPackage.ATTRIBUT__DELEGUE:
        return getDelegue();
      case SimpleJPackage.ATTRIBUT__NAME:
        return getName();
      case SimpleJPackage.ATTRIBUT__TYPE:
        return getType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimpleJPackage.ATTRIBUT__ACCES:
        setAcces((Acces)newValue);
        return;
      case SimpleJPackage.ATTRIBUT__DELEGUE:
        setDelegue((Delegation)newValue);
        return;
      case SimpleJPackage.ATTRIBUT__NAME:
        setName((String)newValue);
        return;
      case SimpleJPackage.ATTRIBUT__TYPE:
        setType((Type)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimpleJPackage.ATTRIBUT__ACCES:
        setAcces(ACCES_EDEFAULT);
        return;
      case SimpleJPackage.ATTRIBUT__DELEGUE:
        setDelegue((Delegation)null);
        return;
      case SimpleJPackage.ATTRIBUT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SimpleJPackage.ATTRIBUT__TYPE:
        setType((Type)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimpleJPackage.ATTRIBUT__ACCES:
        return acces != ACCES_EDEFAULT;
      case SimpleJPackage.ATTRIBUT__DELEGUE:
        return delegue != null;
      case SimpleJPackage.ATTRIBUT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SimpleJPackage.ATTRIBUT__TYPE:
        return type != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (acces: ");
    result.append(acces);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //AttributImpl
