/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.serializer;

import com.google.inject.Inject;
import fr.paris10.miage.services.SimpleJGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SimpleJSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SimpleJGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Classe_RightParenthesisKeyword_3_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SimpleJGrammarAccess) access;
		match_Classe_RightParenthesisKeyword_3_q = new TokenAlias(false, true, grammarAccess.getClasseAccess().getRightParenthesisKeyword_3());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Classe_RightParenthesisKeyword_3_q.equals(syntax))
				emit_Classe_RightParenthesisKeyword_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ')'?
	 *
	 * This ambiguous syntax occurs at:
	 *     attributs+=Attribut (ambiguity) ':' parent=[Classe|ID]
	 *     attributs+=Attribut (ambiguity) (rule end)
	 *     attributs+=Attribut (ambiguity) methodes+=Methode
	 */
	protected void emit_Classe_RightParenthesisKeyword_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
