/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.scoping;

import fr.paris10.miage.scoping.AbstractSimpleJScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SimpleJScopeProvider extends AbstractSimpleJScopeProvider {
}
