/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimpleJScopeProvider extends DelegatingScopeProvider {
}
