/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.simpleJ;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Acces</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see fr.paris10.miage.simpleJ.SimpleJPackage#getAcces()
 * @model
 * @generated
 */
public enum Acces implements Enumerator
{
  /**
   * The '<em><b>Access Var</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESS_VAR_VALUE
   * @generated
   * @ordered
   */
  ACCESS_VAR(0, "accessVar", "var"),

  /**
   * The '<em><b>Access Const</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESS_CONST_VALUE
   * @generated
   * @ordered
   */
  ACCESS_CONST(1, "accessConst", "const"),

  /**
   * The '<em><b>Access Hidden</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESS_HIDDEN_VALUE
   * @generated
   * @ordered
   */
  ACCESS_HIDDEN(2, "accessHidden", "hidden");

  /**
   * The '<em><b>Access Var</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Access Var</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACCESS_VAR
   * @model name="accessVar" literal="var"
   * @generated
   * @ordered
   */
  public static final int ACCESS_VAR_VALUE = 0;

  /**
   * The '<em><b>Access Const</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Access Const</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACCESS_CONST
   * @model name="accessConst" literal="const"
   * @generated
   * @ordered
   */
  public static final int ACCESS_CONST_VALUE = 1;

  /**
   * The '<em><b>Access Hidden</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Access Hidden</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACCESS_HIDDEN
   * @model name="accessHidden" literal="hidden"
   * @generated
   * @ordered
   */
  public static final int ACCESS_HIDDEN_VALUE = 2;

  /**
   * An array of all the '<em><b>Acces</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Acces[] VALUES_ARRAY =
    new Acces[]
    {
      ACCESS_VAR,
      ACCESS_CONST,
      ACCESS_HIDDEN,
    };

  /**
   * A public read-only list of all the '<em><b>Acces</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Acces> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Acces</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Acces get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Acces result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Acces</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Acces getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Acces result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Acces</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Acces get(int value)
  {
    switch (value)
    {
      case ACCESS_VAR_VALUE: return ACCESS_VAR;
      case ACCESS_CONST_VALUE: return ACCESS_CONST;
      case ACCESS_HIDDEN_VALUE: return ACCESS_HIDDEN;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Acces(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Acces
