/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.simpleJ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Methode</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.paris10.miage.simpleJ.Methode#getName <em>Name</em>}</li>
 *   <li>{@link fr.paris10.miage.simpleJ.Methode#getType <em>Type</em>}</li>
 *   <li>{@link fr.paris10.miage.simpleJ.Methode#getAttributs <em>Attributs</em>}</li>
 *   <li>{@link fr.paris10.miage.simpleJ.Methode#getContenu <em>Contenu</em>}</li>
 * </ul>
 *
 * @see fr.paris10.miage.simpleJ.SimpleJPackage#getMethode()
 * @model
 * @generated
 */
public interface Methode extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.paris10.miage.simpleJ.SimpleJPackage#getMethode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.paris10.miage.simpleJ.Methode#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see fr.paris10.miage.simpleJ.SimpleJPackage#getMethode_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link fr.paris10.miage.simpleJ.Methode#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Attributs</b></em>' containment reference list.
   * The list contents are of type {@link fr.paris10.miage.simpleJ.Attribut}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributs</em>' containment reference list.
   * @see fr.paris10.miage.simpleJ.SimpleJPackage#getMethode_Attributs()
   * @model containment="true"
   * @generated
   */
  EList<Attribut> getAttributs();

  /**
   * Returns the value of the '<em><b>Contenu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contenu</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contenu</em>' attribute.
   * @see #setContenu(String)
   * @see fr.paris10.miage.simpleJ.SimpleJPackage#getMethode_Contenu()
   * @model
   * @generated
   */
  String getContenu();

  /**
   * Sets the value of the '{@link fr.paris10.miage.simpleJ.Methode#getContenu <em>Contenu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contenu</em>' attribute.
   * @see #getContenu()
   * @generated
   */
  void setContenu(String value);

} // Methode
