/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.simpleJ;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.paris10.miage.simpleJ.SimpleJFactory
 * @model kind="package"
 * @generated
 */
public interface SimpleJPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simpleJ";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.paris10.fr/miage/SimpleJ";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simpleJ";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleJPackage eINSTANCE = fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.paris10.miage.simpleJ.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.simpleJ.impl.ModelImpl
   * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CLASSES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.paris10.miage.simpleJ.impl.ClasseImpl <em>Classe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.simpleJ.impl.ClasseImpl
   * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getClasse()
   * @generated
   */
  int CLASSE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSE__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSE__ATTRIBUTS = 1;

  /**
   * The number of structural features of the '<em>Classe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.paris10.miage.simpleJ.impl.AttributImpl <em>Attribut</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.simpleJ.impl.AttributImpl
   * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getAttribut()
   * @generated
   */
  int ATTRIBUT = 2;

  /**
   * The feature id for the '<em><b>Acces</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__ACCES = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__TYPE = 2;

  /**
   * The number of structural features of the '<em>Attribut</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.paris10.miage.simpleJ.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.simpleJ.impl.TypeImpl
   * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getType()
   * @generated
   */
  int TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.paris10.miage.simpleJ.Acces <em>Acces</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.simpleJ.Acces
   * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getAcces()
   * @generated
   */
  int ACCES = 4;


  /**
   * Returns the meta object for class '{@link fr.paris10.miage.simpleJ.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.paris10.miage.simpleJ.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.paris10.miage.simpleJ.Model#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see fr.paris10.miage.simpleJ.Model#getClasses()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Classes();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.simpleJ.Classe <em>Classe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Classe</em>'.
   * @see fr.paris10.miage.simpleJ.Classe
   * @generated
   */
  EClass getClasse();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.simpleJ.Classe#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.paris10.miage.simpleJ.Classe#getName()
   * @see #getClasse()
   * @generated
   */
  EAttribute getClasse_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.paris10.miage.simpleJ.Classe#getAttributs <em>Attributs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributs</em>'.
   * @see fr.paris10.miage.simpleJ.Classe#getAttributs()
   * @see #getClasse()
   * @generated
   */
  EReference getClasse_Attributs();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.simpleJ.Attribut <em>Attribut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribut</em>'.
   * @see fr.paris10.miage.simpleJ.Attribut
   * @generated
   */
  EClass getAttribut();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.simpleJ.Attribut#getAcces <em>Acces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Acces</em>'.
   * @see fr.paris10.miage.simpleJ.Attribut#getAcces()
   * @see #getAttribut()
   * @generated
   */
  EAttribute getAttribut_Acces();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.simpleJ.Attribut#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.paris10.miage.simpleJ.Attribut#getName()
   * @see #getAttribut()
   * @generated
   */
  EAttribute getAttribut_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.paris10.miage.simpleJ.Attribut#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see fr.paris10.miage.simpleJ.Attribut#getType()
   * @see #getAttribut()
   * @generated
   */
  EReference getAttribut_Type();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.simpleJ.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see fr.paris10.miage.simpleJ.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.simpleJ.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.paris10.miage.simpleJ.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for enum '{@link fr.paris10.miage.simpleJ.Acces <em>Acces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Acces</em>'.
   * @see fr.paris10.miage.simpleJ.Acces
   * @generated
   */
  EEnum getAcces();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimpleJFactory getSimpleJFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.paris10.miage.simpleJ.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.simpleJ.impl.ModelImpl
     * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CLASSES = eINSTANCE.getModel_Classes();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.simpleJ.impl.ClasseImpl <em>Classe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.simpleJ.impl.ClasseImpl
     * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getClasse()
     * @generated
     */
    EClass CLASSE = eINSTANCE.getClasse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASSE__NAME = eINSTANCE.getClasse_Name();

    /**
     * The meta object literal for the '<em><b>Attributs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASSE__ATTRIBUTS = eINSTANCE.getClasse_Attributs();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.simpleJ.impl.AttributImpl <em>Attribut</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.simpleJ.impl.AttributImpl
     * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getAttribut()
     * @generated
     */
    EClass ATTRIBUT = eINSTANCE.getAttribut();

    /**
     * The meta object literal for the '<em><b>Acces</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUT__ACCES = eINSTANCE.getAttribut_Acces();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUT__NAME = eINSTANCE.getAttribut_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUT__TYPE = eINSTANCE.getAttribut_Type();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.simpleJ.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.simpleJ.impl.TypeImpl
     * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.simpleJ.Acces <em>Acces</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.simpleJ.Acces
     * @see fr.paris10.miage.simpleJ.impl.SimpleJPackageImpl#getAcces()
     * @generated
     */
    EEnum ACCES = eINSTANCE.getAcces();

  }

} //SimpleJPackage
