/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.parser.antlr;

import com.google.inject.Inject;
import fr.paris10.miage.parser.antlr.internal.InternalSimpleJParser;
import fr.paris10.miage.services.SimpleJGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimpleJParser extends AbstractAntlrParser {

	@Inject
	private SimpleJGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleJParser createParser(XtextTokenStream stream) {
		return new InternalSimpleJParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SimpleJGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleJGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
