/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage;

import fr.paris10.miage.SimpleJStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimpleJStandaloneSetup extends SimpleJStandaloneSetupGenerated {
  public static void doSetup() {
    SimpleJStandaloneSetup _simpleJStandaloneSetup = new SimpleJStandaloneSetup();
    _simpleJStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
